### ISSUE TITLE
start_auto_splitter doesn't start split

### ISSUE THREAD

**Issue by Anigif** [Avasam/Auto-Split#11]
I'm quite new to this awesome tool, but I think the `start_auto_splitter`-feature might be broken. As I understand it, if I specify a png-image called `start_auto_splitter.png` that should trigger the start of a new split?

If I add an image called that and press "Reload Start Image" the image is shown in "Current Split Image", but it never triggers any start. It also seems like there isn't any "live similarity" shown, so might be related to that?

Not sure if it's relevant, but I'm using a masked image. It however doesn't seem to make any difference if there's an `{m}` in the file name or not.

I'm using version _v1.5.A6_. Let me know if you want more info as I'm not sure what makes sense to provide.

**Comment by Anigif** [comment]
Don't know if it is because I use it with with Live Split integration, as described [here](https://www.speedrun.com/ptle/guide/lnrso) (with another game though). It however doesn't really seem to make any difference if I start the AutoSplit executable directly. Nothing is triggered and if I start the split manually (by pressing "Start Auto Splitter" - which is greyed out when starting AutoSplit via LiveSplit) it jumps directly to the first non-start image.

**Comment by Avasam** [comment]
@Anigif I believe you are trying to use it correctly. And I know in v1.5.A6 the autostart isn't working perfectly. Also mask flags `{m}` are no longer necessary (the mask is detected from image transparency).

I'm working with Toufool to get version 1.6.0 out pretty soon. It contains a ton of bugfixes and this feature. We're done adding everything we wanted for this release yesterday, so now we're doing one last batch of testing.

**Comment by Anigif** [comment]
Ah, great! I'm happy to hear I'm not doing anything wrong - and sounds really cool with a new version with everything merged. Let me know if you want me to test anything. Thanks a lot for the explanation.
