### ISSUE TITLE
start_auto_splitter starts immediately

### ISSUE THREAD

**Issue by maxlxl** [Avasam/Auto-Split#20]
When using a start_auto_splitter image AutoSplit is not checking the CaptureRegion but instead immediately starting as soon as you click on "Reload Start Image" or on "Reset".

I expect it to start when the image in the capture region matches (respecting the set threshold) the start_auto_splitter image.

I used version [AutoSplit v2.0.0-alpha-avasam-1](https://github.com/Avasam/Auto-Split/releases/tag/v2.0.0-alpha-avasam-1).

**Comment by Avasam** [comment]
I've also been having some issues with the start image, specifically with the `{b}` (below) flag. Could be related. Thanks for raising the issue.

**Comment by maxlxl** [comment]
I'm using one split image with the ```{b}``` flag, but that works for me.
My current workaround is to use the 001_splitimage.png as the actual start image and manually resetting LiveSplit directly. Then the first split starts the LiveSplit timer like expected.

**Comment by Avasam** [comment]
I had just flipped a comparison. Simple issue, will be fixed in the next alpha release.

**Comment by Avasam** [comment]
You can download the artifact from this build: https://github.com/Toufool/Auto-Split/actions/runs/2449476206

**Comment by maxlxl** [comment]
Just tested it and it works as expected now! Thank you!
