### ISSUE TITLE
Autosplit does not work properly with v4l2loopback virtual devices

### ISSUE THREAD

**Issue by Gamebuster19901** [Avasam/Auto-Split#55]
Using `v4l2loopback`, I have created a virtual device, and piped my capture card's output into the new virtual device.

https://askubuntu.com/a/1244152/1061866

Virtual devices created with v4l2loopback can be accessed by multiple programs simultaneously. I'm trying to allow both OBS and Auto-Split to access the new virtual device at `/dev/video5` 

In autosplit, I see two devices with the same name as my capture card:

![image](https://user-images.githubusercontent.com/7155747/210509606-96352bfc-748a-46a9-900a-145257ee6650.png)

When selecting either of these devices, I get the following error:

```
Traceback (most recent call last):

  File "/home/gamebuster/Desktop/autosplit/src/capture_method/CaptureMethodBase.py", line 56, in __read_loop
    self._last_captured_frame, self.__is_old_image = self._read_action(autosplit)

  File "/home/gamebuster/Desktop/autosplit/src/capture_method/VideoCaptureDeviceCaptureMethod.py", line 39, in _read_action
    result, image = self.capture_device.read()

cv2.error: OpenCV(4.7.0) /io/opencv/modules/videoio/src/cap.cpp:349: error: (-2:Unspecified error)  in function 'grab'
```

Other programs are able to access `/dev/video5` simultaneously just fine (in the image below, you see VLC has the device open, and OBS also has it open at the same time.

![image](https://user-images.githubusercontent.com/7155747/210510457-ed0ff228-f799-479b-8e0b-9ff5416a29d5.png)

**Comment by Avasam** [comment]
Thanks for the report. Sorry for the late acknowledgment, I don't remember ever receiving a notification for this.

Last time I touched the Linux port I couldn't see a Virtual Camera in OBS so I was unable to test. Since then my VM got corrupted due to a failing hard drive and I haven't touched the Linux port since. Relates to #41

It will be one of my main focus after the 2.0.0 release is out though.

**Comment by Gamebuster19901** [comment]
I was able to get it to somewhat work at one point but there was a massive delay in obs and autosplit so I just bought a second capture card and an HDMI splitter.

**Comment by Avasam** [comment]
Moved to https://github.com/Toufool/AutoSplit/issues/224
