### ISSUE TITLE
Feature Request: Auto Start on Reset

### ISSUE THREAD

**Issue by Phobic-HR** [Avasam/Auto-Split#57]
Auto start on reset is a feature on the upstream branch. I don't know if it was removed for some reason or during the settings revamp was forgotten about. There is a section for it in the read me of this repository so I can only imply it is not implemented yet. This feature lets my split images(Halo 5) run without any input from the runner. The start image feature would be a good alternative to auto start on reset however the first image is a dummy split. Start image will always hit the split key even with the dummy flag.

I am seeing two solutions to this. Solution one would be to add auto start on reset like how it is on the upstream branch. Solution two is to make the start image work with the dummy flag. Either solution will work for me. Solution one being preferred.

**Comment by Avasam** [comment]
Thanks for the report. Sorry for the late acknowledgment, I don't remember ever receiving a notification for this.

I'm tempted to say using the start image would be the intended solution (same image as reset, so it starts immediately).
That being said, without double-checking I do believe that you are right that the start image ignores the dummy flag. It's an interesting use-case I didn't think of, and one that I believe should have been supported without much complexity.

**Comment by Avasam** [comment]
Moved to https://github.com/Toufool/AutoSplit/issues/222
