### ISSUE TITLE
Unhandled Exception while using Video Capture Device

### ISSUE THREAD

**Issue by dshepsis** [Avasam/Auto-Split#58]
I had AutoSplit open, with my capture card selected as the video stream. My console was off, so there was no signal. When I turned on the console, I got the following error in AutoSplit `Version: 2.0.0-beta.1-2211241633`
```
Traceback (most recent call last):

  File "capture_method\VideoCaptureDeviceCaptureMethod.py", line 41, in __read_loop

cv2.error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\cap.cpp:365: error: (-2:Unspecified error) could not retrieve channel 0 in function 'cv::VideoCapture::retrieve'
```

**Comment by Avasam** [comment]
@dshepsis if you can replicate, could you re-open this with all necessary informations over at https://github.com/Toufool/AutoSplit/issues/new?assignees=&labels=bug&template=bug-or-crash-report.md&title=Unhandled%20Exception%20while%20using%20Video%20Capture%20Device
