### ISSUE TITLE
Not able to use any Video Capture Device

### ISSUE THREAD

**Issue by SiirZax** [Avasam/Auto-Split#61]
Hello, i'm trying to put my OBS virtual camera as capture method but it's not working as soon as I select the "Video Capture Device" option

Here's the error: 
"Traceback (most recent call last):

  File "menu_bar.py", line 303, in <lambda>

  File "menu_bar.py", line 165, in __capture_method_changed

  File "capture_method\__init__.py", line 196, in change_capture_method

  File "capture_method\VideoCaptureDeviceCaptureMethod.py", line 73, in __init__

  File "pygrabber\dshow_graph.py", line 371, in add_video_input_device

  File "pygrabber\dshow_graph.py", line 366, in __add_filter

  File "pygrabber\dshow_graph.py", line 299, in build_filter

  File "pygrabber\dshow_graph.py", line 288, in get_filter_by_index

ValueError: NULL COM pointer access
"

Thank you guys for helping

**Comment by Avasam** [comment]
Hi @SiirZax .
Please see https://github.com/Toufool/AutoSplit#capture-method
> If you want to use this with OBS' Virtual Camera, use the [Virtualcam plugin](https://github.com/Avasam/obs-virtual-cam/releases) instead.

OBS' integrated Virtual Camera is misconfigured and does not work currently work with OpenCV. It is a known issue (see https://github.com/obsproject/obs-studio/issues/3635 and https://github.com/opencv/opencv/issues/19746). It won't be possible until the next release of OpenCV. In the mean time, you'll have to use the virtualcam plugin.

**Comment by Avasam** [comment]
Actually, do you even have any capture device that appear under "Capture device" ?
![image](https://user-images.githubusercontent.com/1350584/234051647-06fed05d-3ca7-4702-a805-a38f0bd267a3.png)

**Comment by SiirZax** [comment]
I have all my video capture device listed, but as soon as i select "video capture device (see below)" I got this error, then none of my video capture device will work, obs one will specifically make it crash

**Comment by Avasam** [comment]
Could you please re-open over at? https://github.com/Toufool/AutoSplit/issues/new/choose
